"""
Simple translation system for web app
"""

TRANSLATIONS = {
    'ru': {
        # Common
        'login': 'Вход',
        'logout': 'Выйти',
        'username': 'Логин',
        'password': 'Пароль',
        'dashboard': 'Панель управления',
        'settings': 'Настройки',
        
        # Teacher Dashboard
        'teacher_dashboard': 'Кабинет учителя',
        'scraper': 'Скрапер',
        'mektep_login': 'Логин/IIN (mektep.edu.kz)',
        'mektep_password': 'Пароль (mektep.edu.kz)',
        'language': 'Язык',
        'quarter': 'Четверть',
        'quarter_1': '1 четверть',
        'quarter_2': '2 четверть (1 полугодие)',
        'quarter_3': '3 четверть',
        'quarter_4': '4 четверть (2 полугодие)',
        'period_year': 'Учебный год',
        'start_button': 'Запустить',
        'progress': 'Прогресс',
        'status': 'Статус',
        'jobs': 'Задачи',
        'reports': 'Отчеты',
        'my_files': 'Мои файлы',
        'goals': 'Цели',
        'download_all': 'Скачать все отчеты',
        'delete_all': 'Удалить все отчеты',
        'class': 'Класс',
        'subject': 'Предмет',
        'download': 'Скачать',
        'number': '№',
        'excel': 'Excel',
        'word': 'Word',
        'no_files': 'Файлов пока нет. Запустите скрапер, чтобы создать отчеты.',
        'apply': 'Применить',
        'cancel': 'Отмена',
        'goals_modal_title': 'Цели обучения',
        'select_reports': 'Выберите отчеты для применения:',
        'no_reports_available': 'Нет доступных отчетов',
        'goals_difficulties': 'Цели, вызвавшие затруднения',
        'achieved_goals': 'Цели, которые были достигнуты',
        'difficulties_list': 'Перечень затруднений, которые возникли у обучающихся при выполнении заданий',
        'reasons': 'Причины, указанных выше затруднений у обучающихся при выполнении заданий',
        'correction': 'Планируемая коррекционная работа',
        'difficulties_correction_title': 'Затруднения и коррекционная работа',

        # Admin Dashboard
        'admin_panel': 'Панель управления',
        'grades_overview': 'Обзор оценок',
        'grades_overview_desc': 'Сводные таблицы по классам',
        'analytics_sor_soch': 'Аналитика СОР/СОЧ',
        'analytics_sor_soch_desc': 'Анализ суммативного оценивания',
        'class_teacher_report': 'Отчёт кл. руководителя',
        'student_categories': 'Категории учеников',
        'management': 'Управление',
        'management_desc': 'Учителя, классы, предметы',
        'criteria_assessment': 'Критериальное оценивание',
        'criteria_assessment_desc': 'Детализация ФО, СОР, СОЧ и итоговых оценок по предметам',
        'criteria_download_excel_all': 'Скачать Excel (все классы)',
        'period_final': 'Итог',
        'criteria_final_placeholder': 'Нет данных итога. Запустите скрап с периодом «Итог» в десктоп-приложении.',
        'criteria_no_data_period': 'Нет данных за выбранный период. Загрузите отчёты с десктоп-приложения.',
        'criteria_no_data': 'Нет данных для отображения.',
        'criteria_reupload_hint': 'Детализация критериев недоступна для этого отчёта. Перезагрузите отчёт с десктоп-приложения (после обновления).',
        'criteria_open_class': 'Предметы',
        'criteria_open_table': 'Таблица',
        'criteria_back_classes': 'К классам',
        'criteria_back_subjects': 'К предметам',
        'criteria_year_hint': 'За учебный год показаны только итоговые оценки (без % и без детализации ФО/СОР).',
        'subject_dictionary': 'Словарь предметов',
        'subject_dictionary_desc': 'Казахские и альтернативные названия → канон на русском для сводных таблиц',
        'subject_alias_kk': 'Вариант (каз./альт.)',
        'subject_canonical_ru': 'Канон (рус.)',
        'subject_alias_placeholder': 'Напр. Қазақ тілі мен әдебиеті',
        'subject_canonical_placeholder': 'Напр. Казахский язык и литература',
        'restore_subject_dictionary': 'Восстановить стандартный словарь',
        'no_subject_aliases': 'Словарь пуст. Добавьте запись или восстановите стандартный словарь.',
        'confirm_delete_subject_alias': 'Удалить эту запись из словаря?',
        'edit_subject_alias': 'Редактировать запись словаря',
        'teachers': 'Учителя',
        'classes': 'Классы',
        'teacher_fio': 'ФИО учителя',
        'teacher_iin_col': 'ИИН',
        'teacher_iin_placeholder': 'ИИН (12 цифр, как на mektep.edu.kz)',
        'teacher_iin_title': 'Индивидуальный идентификационный номер для входа на mektep.edu.kz',
        'teacher_iin_label': 'ИИН (ЖСН)',
        'edit_teacher_title': 'Редактировать учителя',
        'teacher_login': 'Логин учителя',
        'add_btn': '+ Добавить',
        'fio': 'ФИО',
        'login_col': 'Логин',
        'actions': 'Действия',
        'password_btn': 'Пароль',
        'class_name_placeholder': 'Название класса (напр. 7А)',
        'class_teacher': 'Классный руководитель',
        'classes_1_4': 'Классы 1–4',
        'classes_5_9': 'Классы 5–9',
        'classes_10_11': 'Классы 10–11',
        'no_class_leadership': 'Без классного руководства',
        'not_assigned': '— не назначен —',
        'no_classes': 'Нет классов. Добавьте класс выше.',
        'edit_class': 'Редактировать класс',
        'edit_teacher_fio': 'Редактировать ФИО учителя',
        'class_name_label': 'Название класса:',
        'class_teacher_label': 'Классный руководитель:',
        'fio_label': 'ФИО:',
        'save_btn': 'Сохранить',
        'cancel_btn': 'Отмена',
        'password_label': 'Пароль:',
        'current_password': 'Текущий пароль:',
        'new_password': 'Новый пароль:',
        'min_4_chars': 'Минимум 4 символа',
        'change_password': 'Изменить пароль',
        'copy_btn': 'Копировать',
        'copied': 'Скопировано!',
        'loading_text': 'Загрузка...',
        'load_error': 'Ошибка загрузки',
        'not_available': 'Недоступен',
        'confirm_delete_teacher': 'Вы уверены, что хотите удалить учителя "{}"?\n\nВсе данные учителя (отчёты, назначения) будут удалены безвозвратно.',
        'confirm_delete_class': (
            'Удалить класс «{}» из списка?\n\n'
            'Загруженные оценки и файлы отчётов не удаляются. '
            'Их можно удалить отдельно в разделе «Обзор оценок».'
        ),
        'school_kpi_title': 'Показатели школы',
        'school_kpi_hint': 'Средние качество и успеваемость по четвертным отчётам (простое среднее арифметическое по предметам внутри класса и по классам внутри школы).',
        'school_kpi_no_data': 'За выбранную четверть нет данных: учителя ещё не загрузили отчёты или классы не совпадают.',
        'year_kpi_title': 'Годовые итоги',
        'year_kpi_hint': 'Средние качество и успеваемость за учебный год: годовая оценка — среднее по загруженным четвертям (сумма / их количество, округление), KPI по классу — из всех годовых оценок учеников.',
        'year_kpi_no_data': 'За учебный год пока нет данных: загрузите отчёты хотя бы за одну четверть (1–4).',
        'school_kpi_classes_with_data': 'Классов с данными',
        'school_kpi_detail_charts': 'Диаграммы и таблицы по классам',

        # Grades Overview
        'period_type': 'Тип периода',
        'quarter_label': 'Четверть',
        'semester_label': 'Полугодие',
        'period_number': 'Номер периода',
        'quarter_suffix': 'четверть',
        'semester_suffix': 'полугодие',
        'apply_btn': 'Применить',
        'class_col': 'Класс',
        'students_count': 'Кол-во учеников',
        'subjects': 'Предметы',
        'subjects_count': 'предметов',
        'summary_table': 'Сводная таблица',
        'no_data_period': 'Нет данных за выбранный период. Учителя ещё не загрузили отчёты.',

        # Analytics
        'analytics': 'Анализы',
        'analytics_desc': 'Просмотр статистики по предметам',
        'all_subjects': 'Все предметы',
        'all_classes': 'Все классы',
        'teacher_col': 'Учитель',
        'all_teachers': 'Все учителя',
        'reset_filters': 'Сбросить фильтры',
        'sor': 'СОР',
        'soch': 'СОЧ',
        'grades': 'Оценки',
        'total': 'Всего',
        'quality_pct': 'Качество, %',
        'success_pct': 'Успеваемость, %',
        'no_data_sor': 'Нет данных по СОР.',
        'no_data_soch': 'Нет данных по СОЧ.',
        'no_data_grades': 'Нет данных по оценкам.',

        # Class Teacher Report
        'class_teacher_full_report': 'Отчет классных руководителей',
        'download_excel': 'Скачать Excel',
        'on_5': 'на 5',
        'on_4': 'на 4',
        'with_one_4': 'С одной 4',
        'on_3': 'на 3',
        'with_one_3': 'С одной 3',
        'underachievers': 'Неуспевающие',
        'search_placeholder': 'Поиск по классу или ФИО...',
        'subject_col': 'Предмет',
        'subject_1': 'Предмет 1',
        'subject_2': 'Предмет 2',
        'subject_3': 'Предмет 3',
        'subject_4': 'Предмет 4',
        'subject_5plus': 'Предмет 5+',
        'no_data': 'Нет данных',

        # Grades Class (summary table)
        'summary_table_grades': 'Сводная таблица оценок',
        'total_students': 'Всего учеников',
        'quality_label': 'Качество',
        'success_label': 'Успеваемость',
        'distribution': 'Распределение',
        'grades_by_subjects': 'Оценки по предметам',
        'student_fio': 'ФИО ученика',
        'count_5': 'Кол-во «5»',
        'count_4': 'Кол-во «4»',
        'count_3': 'Кол-во «3»',
        'count_2': 'Кол-во «2»',
        'quality_pct_label': 'Качество %',
        'success_pct_label': 'Успеваемость %',
        'no_data_class_grades': 'Нет данных по оценкам для этого класса.',

        # Subject Detail
        'all_subjects_sidebar': 'Все предметы',
        'subject_teachers': 'Учителя предмета',
        'select_teacher': '— Выберите учителя —',
        'add_teacher': 'Добавить учителя',
        'remove_btn': 'Убрать',
        'confirm_remove_teacher': 'Удалить учителя «{}» из предмета? Все закреплённые классы также будут удалены.',
        'assigned_classes': 'Закреплённые классы:',
        'subgroup': 'Подгруппа',
        'subgroup_label': 'Подгруппа',
        'whole_class': 'Весь класс',
        'confirm_unassign_class': 'Открепить класс {}?',
        'no_assigned_classes': 'Нет закреплённых классов',
        'select_class': '— Выберите класс —',
        'assign_class': 'Закрепить класс',
        'no_subject_teachers': 'Нет учителей для этого предмета. Добавьте учителя выше.',

        # Password page
        'user_password': 'Пароль пользователя',
        'password_unavailable': 'Пароль недоступен',
        'back_btn': 'Назад',

        # School Detail (superadmin)
        'superadmin': 'Супер-админ',
        'active_status': 'Активна',
        'inactive_status': 'Неактивна',
        'admins_count_label': 'Админов',
        'teachers_count_label': 'Учителей',
        'classes_count_label': 'Классов',
        'subjects_count_label': 'Предметов',
        'administrators': 'Администраторы',
        'no_admins': 'Нет администраторов',
        'name_col': 'Имя',
        'no_teachers': 'Нет учителей',
        'no_classes_short': 'Нет классов',
        'teachers_badge': 'учителей',
        'no_subjects': 'Нет предметов (данные появятся после скрапинга)',

        # Superadmin Dashboard
        'super_admin': 'Super Admin',
        'teacher_cabinet_reports': 'Кабинет учителя / Создание отчётов',
        'schools': 'Школы',
        'new_school_placeholder': 'Название новой школы',
        'add_short': 'Добавить',
        'open_status': 'Открыт',
        'closed_status': 'Закрыт',
        'settings_btn': 'Настройки',
        'close_school': 'Закрыть',
        'open_school': 'Открыть',
        'delete_btn': 'Удалить',
        'scrape_limit_label': 'Лимит скрапов / четверть',
        'ai_api_key_label': 'AI API ключ',
        'ai_model_label': 'Модель AI',
        'reset_counter': 'Сбросить счётчик',
        'confirm_reset_counter': 'Сбросить счётчик скрапов для «{}»?',
        'no_schools': 'Школы ещё не добавлены.',
        'school_admins': 'Админы школ',
        'select_school': 'Выберите школу…',
        'admin_fio_placeholder': 'ФИО админа',
        'admin_login_placeholder': 'Логин нового админа',
        'school_col': 'Школа',
        'no_school_admins': 'Админы ещё не добавлены.',
        'edit_admin_fio': 'Редактировать ФИО администратора',
        'confirm_delete_admin': 'Вы уверены, что хотите удалить администратора "{}"?\n\nЭто действие необратимо.',
        'confirm_delete_school': 'Вы уверены, что хотите удалить школу "{}"?\n\nБудут удалены ВСЕ данные: учителя, админы, классы, отчёты.\n\nЭто действие необратимо!',

        # Class metrics charts (page + Excel)
        'metrics_page_title': 'Статистика по классам',
        'metrics_page_subtitle': 'Столбчатые диаграммы качества и успеваемости',
        'metrics_tab_overall': 'Общее',
        'metrics_tab_parallel': 'По параллелям',
        'metrics_download_overall': 'Скачать Excel — Общее',
        'metrics_download_parallel': 'Скачать Excel — По параллелям',
        'metrics_card_1_4': '1-4 классы',
        'metrics_card_5_9': '5-9 классы',
        'metrics_card_9_11': '9-11 классы',
        'metrics_card_9': '9 класс',
        'metrics_card_11': '11 класс',
        'metrics_empty_1_4': 'Нет данных для группы 1-4 классов.',
        'metrics_empty_5_9': 'Нет данных для группы 5-9 классов.',
        'metrics_empty_9_11': 'Нет данных для группы 9-11 классов.',
        'metrics_empty_9': 'Нет данных для 9 классов.',
        'metrics_empty_11': 'Нет данных для 11 классов.',
        'metrics_no_charts': 'Нет данных для построения диаграмм.',
        'metrics_col_indicator': 'Показатель',
        'metrics_col_total': 'Итого',
        'metrics_row_quality': 'Качество, %',
        'metrics_row_success': 'Успеваемость, %',
        'metrics_chart_quality': 'Качество',
        'metrics_chart_success': 'Успеваемость',
        'metrics_class_word': 'класс',
        'metrics_parallel_empty': 'Нет данных для {grade} класса.',
        'metrics_excel_sheet_tables': 'Таблицы',
        'metrics_excel_period_q1': '1-я четверть',
        'metrics_excel_period_q2': '2-я четверть',
        'metrics_excel_period_q3': '3-я четверть',
        'metrics_excel_period_q4': '4-я четверть',
        'metrics_excel_period_year': 'Учебный год',
        'metrics_excel_period_fallback': '{n}-я четверть',
        'metrics_excel_title': 'Статистика по классам',
        'metrics_excel_subtitle': 'Качество и успеваемость по классам',
        'metrics_excel_note_overall': 'Таблицы и сводка — на этом листе; гистограммы — на следующих (данные отсюда).',
        'metrics_excel_note_parallel': 'Таблицы по параллелям — на этом листе; гистограммы — на следующих.',
        'metrics_excel_section_overall': 'Общее',
        'metrics_excel_section_parallel': 'По параллелям',
        'metrics_excel_section_summary': 'Сводка',
        'metrics_excel_sec_1_4': '1-4 классы',
        'metrics_excel_sec_5_9': '5-9 классы',
        'metrics_excel_sec_9_11': '9-11 классы',
        'metrics_excel_sec_9': '9 класс',
        'metrics_excel_sec_11': '11 класс',
        'metrics_excel_empty_1_4': 'Нет данных для группы 1-4 классов.',
        'metrics_excel_empty_5_9': 'Нет данных для группы 5-9 классов.',
        'metrics_excel_empty_9_11': 'Нет данных для группы 9-11 классов.',
        'metrics_excel_empty_9': 'Нет данных для 9 классов.',
        'metrics_excel_empty_11': 'Нет данных для 11 классов.',
        'metrics_excel_school_weighted': 'По школе (среднее арифметическое)',
        'metrics_excel_parallel_1_4': 'Параллели 1–4',
        'metrics_excel_parallel_5_9': 'Параллели 5–9',
        'metrics_excel_parallel_10_11': 'Параллели 10–11',
        'metrics_excel_fn_pattern': 'Статистика_классы_{period}ч__{suffix}.xlsx',
        'metrics_excel_fn_suf_o': 'общее',
        'metrics_excel_fn_suf_p': 'по_параллелям',

        # Final school report
        'final_report_title': 'Итоговый отчёт школы',
        'final_report_input_title': 'Итоговый отчёт — ввод данных',
        'final_report_input_hint': 'Аттестаты и отличники (данные для ручного уточнения)',
        'final_report_input_nav_desc': 'Аттестаты и отличники',
        'final_report_export_btn': 'Сформировать итоговый отчёт',
        'final_report_export_desc': 'Excel со сводкой, графиками и динамикой',
        'final_report_tab_awards': 'Аттестаты',
        'final_report_awards_hint': 'Аттестаты с отличием и «Алтын белгі»',
        'final_report_awards_altyn': 'Алтын белгі',
        'final_report_awards_excellent_11': 'С отличием (11 кл.)',
        'final_report_awards_excellent_9': 'С отличием (9 кл.)',
        'final_report_awards_students': 'Список отличников (JSON)',
        'final_report_awards_students_hint': 'Пример: [{"name":"Иванов И.","award":"altyn_belgi"}]',
        'final_report_sheet_summary': 'Сводка',
        'final_report_sheet_dynamics': 'Динамика численности',
        'final_report_sheet_enrollment': 'Численность',
        'final_report_sheet_classes': 'Успеваемость по классам',
        'final_report_sheet_parallels': 'По ступеням',
        'final_report_sheet_quarters': 'По четвертям',
        'final_report_sheet_subjects': 'Качество по предметам',
        'final_report_sheet_problems': 'Проблемные зоны',
        'final_report_sheet_excellent': 'Отличники',
        'final_report_sheet_awards': 'Аттестаты',
        'final_report_sheet_gia9': 'ГИА-9',
        'final_report_sheet_gia11': 'ГИА-11',
        'final_report_sheet_ent': 'ЕНТ',
        'final_report_chart_ent': 'Динамика ЕНТ',
        'final_report_ent_col_period': 'Период',
        'final_report_ent_col_count': 'Кол-во сдававших',
        'final_report_ent_col_avg': 'Средний балл',
        'final_report_ent_col_max': 'Максимум',
        'final_report_ent_forecast': 'Прогноз среднего балла',
        'final_report_recommendations': 'Рекомендации',
        'final_report_chart_quarters': 'Динамика по четвертям',
        'final_report_col_total_students': 'Всего учащихся',
        'final_report_col_total_classes': 'Классов-комплектов',
        'final_report_col_avg_fill': 'Средняя наполняемость',
        'final_report_col_students': 'Учащихся',
        'final_report_col_on_5': 'На «5»',
        'final_report_col_on_4': 'На «4»',
        'final_report_col_one_3': 'С одной «3»',
        'final_report_col_two_3': 'Более двух «3»',
        'final_report_col_on_3': 'На «3»',
        'final_report_col_on_2': 'На «2»',
        'final_report_col_stage': 'Ступень',
        'final_report_col_classes_with_data': 'Классов с данными',
        'final_report_col_student_name': 'ФИО',
        'final_report_col_award_type': 'Тип аттестата',
        'final_report_rec_weak': 'Организовать работу со слабоуспевающими детьми',
        'final_report_rec_math': 'Провести контрольные срезы по математике через месяц после начала года',
        'final_report_dynamics_title': 'ДИНАМИКА ЧИСЛЕННОСТИ КОНТИНГЕНТА УЧАЩИХСЯ ЗА 3 года',
        'final_report_col_parameters': 'Параметры',
        'final_report_students_begin': 'Количество учащихся на начало года:',
        'final_report_students_end': 'Количество учащихся на конец года:',
        'final_report_class_sets_begin': 'Классы-комплекты на начало года:',
        'final_report_avg_fill': 'Средняя наполняемость классов:',
        'final_report_stage_primary': 'начальная школа',
        'final_report_stage_basic': 'основная школа',
        'final_report_stage_secondary': 'средняя школа',
        'final_report_no_data': '-',
        'final_report_sheet_quality': 'Качество по ступеням',
        'final_report_quality_title': 'ПОКАЗАТЕЛИ КАЧЕСТВА ЗНАНИЙ ПО СТУПЕНЯМ ОБУЧЕНИЯ',
        'final_report_hdr_q1': '1 четверть',
        'final_report_hdr_q2': '2 четверть',
        'final_report_hdr_q3': '3 четверть',
        'final_report_hdr_q4': '4 четверть',
        'final_report_hdr_total': 'Итог',
        'final_report_grade_row_5': '«5»',
        'final_report_grade_row_4': '«4»',
        'final_report_grade_row_3': '«3»',
        'final_report_grade_row_2': '«2»',
        'final_report_chart_grades_2_11': 'Общая динамика 2-11 классы',
        'final_report_chart_quality_2_11': 'Общая динамика качества знаний и успеваемости 2-11 классы',
        'final_report_chart_y_students': 'Количество учеников',
        'final_report_chart_y_percent': 'Проценты (%)',
        'academic_year_label': 'Учебный год',
        'notes_label': 'Примечания',
        'save': 'Сохранить',

        # Cross-school reports protection
        'cross_school_label': 'Отчёты для других школ',
        'cross_school_description': 'Если выключено — учитель может создавать отчёты только для своей организации. Защита от передачи аккаунта.',
        'cross_school_enabled': 'Разрешено (выключить)',
        'cross_school_disabled': 'Запрещено (включить)',
    },
    'kk': {
        # Common
        'login': 'Кіру',
        'logout': 'Шығу',
        'username': 'Логин',
        'password': 'Құпия сөз',
        'dashboard': 'Басқару панелі',
        'settings': 'Баптаулар',
        
        # Teacher Dashboard
        'teacher_dashboard': 'Мұғалім кабинеті',
        'scraper': 'Скрапер',
        'mektep_login': 'Логин/ЖСН (mektep.edu.kz)',
        'mektep_password': 'Құпия сөз (mektep.edu.kz)',
        'language': 'Тіл',
        'quarter': 'Тоқсан',
        'quarter_1': '1 тоқсан',
        'quarter_2': '2 тоқсан (1 жартыжылдық)',
        'quarter_3': '3 тоқсан',
        'quarter_4': '4 тоқсан (2 жартыжылдық)',
        'period_year': 'Оқу жылы',
        'start_button': 'Іске қосу',
        'progress': 'Прогресс',
        'status': 'Күй',
        'jobs': 'Тапсырмалар',
        'reports': 'Есептер',
        'my_files': 'Менің файлдарым',
        'goals': 'Мақсаттар',
        'download_all': 'Барлық есептерді жүктеу',
        'delete_all': 'Барлық есептерді жою',
        'class': 'Сынып',
        'subject': 'Пән',
        'download': 'Жүктеу',
        'number': '№',
        'excel': 'Excel',
        'word': 'Word',
        'no_files': 'Файлдар әзірге жоқ. Есептер жасау үшін скраперді іске қосыңыз.',
        'apply': 'Қолдану',
        'cancel': 'Болдырмау',
        'goals_modal_title': 'Оқыту мақсаттары',
        'select_reports': 'Қолдану үшін есептерді таңдаңыз:',
        'no_reports_available': 'Қолжетімді есептер жоқ',
        'goals_difficulties': 'Қиындық тудырған мақсаттар',
        'achieved_goals': 'Қол жеткізілген мақсаттар',
        'difficulties_list': 'Оқушылардың тапсырмаларды орындау кезіндегі туындаған қиындықтар тізбесі',
        'reasons': 'Қиындықтардың себептері',
        'correction': 'БЖБ талдау қорытындылары бойынша жоспарланған жұмыс',
        'difficulties_correction_title': 'Қиындықтар және түзету жұмысы',

        # Admin Dashboard
        'admin_panel': 'Басқару панелі',
        'grades_overview': 'Бағаларға шолу',
        'grades_overview_desc': 'Сыныптар бойынша жиынтық кестелер',
        'analytics_sor_soch': 'БЖБ/ТЖБ аналитикасы',
        'analytics_sor_soch_desc': 'Жиынтық бағалауды талдау',
        'class_teacher_report': 'Сынып жетекшісі есебі',
        'student_categories': 'Оқушылар санаттары',
        'management': 'Басқару',
        'management_desc': 'Мұғалімдер, сыныптар, пәндер',
        'criteria_assessment': 'Критериалды бағалау',
        'criteria_assessment_desc': 'Пәндер бойынша ФО, ББЖ, ТЖБ және қорытынды бағалар',
        'criteria_download_excel_all': 'Excel жүктеу (барлық сынып)',
        'period_final': 'Қорытынды',
        'criteria_final_placeholder': 'Қорытынды деректері жоқ. Десктопта «Қорытынды» кезеңімен скрап іске қосыңыз.',
        'criteria_no_data_period': 'Таңдалған кезеңде деректер жоқ. Десктоп-қосымшадан есептерді жүктеңіз.',
        'criteria_no_data': 'Көрсетуге деректер жоқ.',
        'criteria_reupload_hint': 'Бұл есеп үшін критерийлер жоқ. Десктоп-қосымшадан есепті қайта жүктеңіз (жаңартудан кейін).',
        'criteria_open_class': 'Пәндер',
        'criteria_open_table': 'Кесте',
        'criteria_back_classes': 'Сыныптарға',
        'criteria_back_subjects': 'Пәндерге',
        'criteria_year_hint': 'Оқу жылы үшін тек қорытынды бағалар көрсетіледі (% және ФО/ББЖ жоқ).',
        'subject_dictionary': 'Пәндер сөздігі',
        'subject_dictionary_desc': 'Қазақша / балама атаулар → жиынтық кестелердегі орысша канон',
        'subject_alias_kk': 'Нұсқа (қаз./балама)',
        'subject_canonical_ru': 'Канон (орыс.)',
        'subject_alias_placeholder': 'Мыс. Қазақ тілі мен әдебиеті',
        'subject_canonical_placeholder': 'Мыс. Казахский язык и литература',
        'restore_subject_dictionary': 'Стандартты сөздікті қалпына келтіру',
        'no_subject_aliases': 'Сөздік бос. Жазба қосыңыз немесе стандартты сөздікті қалпына келтіріңіз.',
        'confirm_delete_subject_alias': 'Бұл жазбаны сөздіктен жою керек пе?',
        'edit_subject_alias': 'Сөздік жазбасын өңдеу',
        'teachers': 'Мұғалімдер',
        'classes': 'Сыныптар',
        'teacher_fio': 'Мұғалімнің аты-жөні',
        'teacher_iin_col': 'ЖСН',
        'teacher_iin_placeholder': 'ЖСН (12 сан, mektep.edu.kz сияқты)',
        'teacher_iin_title': 'mektep.edu.kz кіру үшін жеке сәйкестендіру нөмірі',
        'teacher_iin_label': 'ЖСН (ИИН)',
        'edit_teacher_title': 'Мұғалімді өңдеу',
        'teacher_login': 'Мұғалімнің логині',
        'add_btn': '+ Қосу',
        'fio': 'Аты-жөні',
        'login_col': 'Логин',
        'actions': 'Әрекеттер',
        'password_btn': 'Құпия сөз',
        'class_name_placeholder': 'Сынып атауы (мыс. 7А)',
        'class_teacher': 'Сынып жетекшісі',
        'classes_1_4': '1–4 сыныптар',
        'classes_5_9': '5–9 сыныптар',
        'classes_10_11': '10–11 сыныптар',
        'no_class_leadership': 'Сынып жетекшісіз',
        'not_assigned': '— тағайындалмаған —',
        'no_classes': 'Сыныптар жоқ. Жоғарыдан сынып қосыңыз.',
        'edit_class': 'Сыныпты өңдеу',
        'edit_teacher_fio': 'Мұғалімнің аты-жөнін өңдеу',
        'class_name_label': 'Сынып атауы:',
        'class_teacher_label': 'Сынып жетекшісі:',
        'fio_label': 'Аты-жөні:',
        'save_btn': 'Сақтау',
        'cancel_btn': 'Болдырмау',
        'password_label': 'Құпия сөз:',
        'current_password': 'Ағымдағы құпия сөз:',
        'new_password': 'Жаңа құпия сөз:',
        'min_4_chars': 'Кемінде 4 таңба',
        'change_password': 'Құпия сөзді өзгерту',
        'copy_btn': 'Көшіру',
        'copied': 'Көшірілді!',
        'loading_text': 'Жүктелуде...',
        'load_error': 'Жүктеу қатесі',
        'not_available': 'Қолжетімсіз',
        'confirm_delete_teacher': 'Сіз "{}" мұғалімін жоюға сенімдісіз бе?\n\nМұғалімнің барлық деректері (есептер, тағайындаулар) қайтарымсыз жойылады.',
        'confirm_delete_class': (
            '«{}» сыныбын тізімнен жою керек пе?\n\n'
            'Жүктелген бағалар мен есеп файлдары жойылмайды. '
            'Оларды «Бағаларға шолу» бөлімінде бөлек жоюға болады.'
        ),
        'school_kpi_title': 'Мектеп көрсеткіштері',
        'school_kpi_hint': 'Тоқсандық есептер бойынша сапа мен оқу сәттілігінің орташа мәндері (сынып ішіндегі пәндер және мектеп ішіндегі сыныптар бойынша жай арифметикалық орташа).',
        'school_kpi_no_data': 'Таңдалған тоқсанға дерек жоқ: оқытушылар есептерді жүктемеген немесе сыныптар сәйкес келмейді.',
        'year_kpi_title': 'Оқу жылы бойынша қорытындылар',
        'year_kpi_hint': 'Оқу жылы бойынша сапа мен оқу сәттілігі: жылдық баға — жүктелген тоқсандардың орташа арифметикалық мәні (қосынды / саны, дөруге).',
        'year_kpi_no_data': 'Оқу жылы бойынша әзірше дерек жоқ: кем дегенде бір тоқсан (1–4) бойынша есеп жүктеңіз.',
        'school_kpi_classes_with_data': 'Дерегі бар сыныптар',
        'school_kpi_detail_charts': 'Сыныптар бойынша диаграммалар мен кестелер',

        # Grades Overview
        'period_type': 'Кезең түрі',
        'quarter_label': 'Тоқсан',
        'semester_label': 'Жартыжылдық',
        'period_number': 'Кезең нөмірі',
        'quarter_suffix': 'тоқсан',
        'semester_suffix': 'жартыжылдық',
        'apply_btn': 'Қолдану',
        'class_col': 'Сынып',
        'students_count': 'Оқушылар саны',
        'subjects': 'Пәндер',
        'subjects_count': 'пән',
        'summary_table': 'Жиынтық кесте',
        'no_data_period': 'Таңдалған кезең бойынша деректер жоқ. Мұғалімдер есептерді әлі жүктемеген.',

        # Analytics
        'analytics': 'Талдаулар',
        'analytics_desc': 'Пәндер бойынша статистиканы қарау',
        'all_subjects': 'Барлық пәндер',
        'all_classes': 'Барлық сыныптар',
        'teacher_col': 'Мұғалім',
        'all_teachers': 'Барлық мұғалімдер',
        'reset_filters': 'Сүзгілерді қалпына келтіру',
        'sor': 'БЖБ',
        'soch': 'ТЖБ',
        'grades': 'Бағалар',
        'total': 'Барлығы',
        'quality_pct': 'Сапа, %',
        'success_pct': 'Үлгерім, %',
        'no_data_sor': 'БЖБ бойынша деректер жоқ.',
        'no_data_soch': 'ТЖБ бойынша деректер жоқ.',
        'no_data_grades': 'Бағалар бойынша деректер жоқ.',

        # Class Teacher Report
        'class_teacher_full_report': 'Сынып жетекшілерінің есебі',
        'download_excel': 'Excel жүктеу',
        'on_5': '5-ке',
        'on_4': '4-ке',
        'with_one_4': 'Бір 4-пен',
        'on_3': '3-ке',
        'with_one_3': 'Бір 3-пен',
        'underachievers': 'Үлгермейтіндер',
        'search_placeholder': 'Сынып немесе аты-жөні бойынша іздеу...',
        'subject_col': 'Пән',
        'subject_1': 'Пән 1',
        'subject_2': 'Пән 2',
        'subject_3': 'Пән 3',
        'subject_4': 'Пән 4',
        'subject_5plus': 'Пән 5+',
        'no_data': 'Деректер жоқ',

        # Grades Class (summary table)
        'summary_table_grades': 'Бағалардың жиынтық кестесі',
        'total_students': 'Барлық оқушылар',
        'quality_label': 'Сапа',
        'success_label': 'Үлгерім',
        'distribution': 'Бөлу',
        'grades_by_subjects': 'Пәндер бойынша бағалар',
        'student_fio': 'Оқушының аты-жөні',
        'count_5': '«5» саны',
        'count_4': '«4» саны',
        'count_3': '«3» саны',
        'count_2': '«2» саны',
        'quality_pct_label': 'Сапа %',
        'success_pct_label': 'Үлгерім %',
        'no_data_class_grades': 'Бұл сынып бойынша бағалар деректері жоқ.',

        # Subject Detail
        'all_subjects_sidebar': 'Барлық пәндер',
        'subject_teachers': 'Пән мұғалімдері',
        'select_teacher': '— Мұғалімді таңдаңыз —',
        'add_teacher': 'Мұғалім қосу',
        'remove_btn': 'Алып тастау',
        'confirm_remove_teacher': '«{}» мұғалімін пәннен жою керек пе? Барлық бекітілген сыныптар да жойылады.',
        'assigned_classes': 'Бекітілген сыныптар:',
        'subgroup': 'Топша',
        'subgroup_label': 'Топша',
        'whole_class': 'Бүкіл сынып',
        'confirm_unassign_class': '{} сыныбын ажырату керек пе?',
        'no_assigned_classes': 'Бекітілген сыныптар жоқ',
        'select_class': '— Сыныпты таңдаңыз —',
        'assign_class': 'Сыныпты бекіту',
        'no_subject_teachers': 'Бұл пәнде мұғалімдер жоқ. Жоғарыдан мұғалім қосыңыз.',

        # Password page
        'user_password': 'Пайдаланушы құпия сөзі',
        'password_unavailable': 'Құпия сөз қолжетімсіз',
        'back_btn': 'Артқа',

        # School Detail (superadmin)
        'superadmin': 'Супер-админ',
        'active_status': 'Белсенді',
        'inactive_status': 'Белсенді емес',
        'admins_count_label': 'Әкімшілер',
        'teachers_count_label': 'Мұғалімдер',
        'classes_count_label': 'Сыныптар',
        'subjects_count_label': 'Пәндер',
        'administrators': 'Әкімшілер',
        'no_admins': 'Әкімшілер жоқ',
        'name_col': 'Аты',
        'no_teachers': 'Мұғалімдер жоқ',
        'no_classes_short': 'Сыныптар жоқ',
        'teachers_badge': 'мұғалім',
        'no_subjects': 'Пәндер жоқ (деректер скрапингтен кейін пайда болады)',

        # Superadmin Dashboard
        'super_admin': 'Super Admin',
        'teacher_cabinet_reports': 'Мұғалім кабинеті / Есептер жасау',
        'schools': 'Мектептер',
        'new_school_placeholder': 'Жаңа мектеп атауы',
        'add_short': 'Қосу',
        'open_status': 'Ашық',
        'closed_status': 'Жабық',
        'settings_btn': 'Баптаулар',
        'close_school': 'Жабу',
        'open_school': 'Ашу',
        'delete_btn': 'Жою',
        'scrape_limit_label': 'Скрап лимиті / тоқсан',
        'ai_api_key_label': 'AI API кілті',
        'ai_model_label': 'AI моделі',
        'reset_counter': 'Есептегішті қалпына келтіру',
        'confirm_reset_counter': '«{}» үшін скрап есептегішін қалпына келтіру керек пе?',
        'no_schools': 'Мектептер әлі қосылмаған.',
        'school_admins': 'Мектеп әкімшілері',
        'select_school': 'Мектепті таңдаңыз…',
        'admin_fio_placeholder': 'Әкімші аты-жөні',
        'admin_login_placeholder': 'Жаңа әкімші логині',
        'school_col': 'Мектеп',
        'no_school_admins': 'Әкімшілер әлі қосылмаған.',
        'edit_admin_fio': 'Әкімші аты-жөнін өңдеу',
        'confirm_delete_admin': 'Сіз "{}" әкімшісін жоюға сенімдісіз бе?\n\nБұл әрекет қайтарымсыз.',
        'confirm_delete_school': 'Сіз "{}" мектебін жоюға сенімдісіз бе?\n\nБАРЛЫҚ деректер жойылады: мұғалімдер, әкімшілер, сыныптар, есептер.\n\nБұл әрекет қайтарымсыз!',

        # Class metrics charts (page + Excel)
        'metrics_page_title': 'Сыныптар бойынша статистика',
        'metrics_page_subtitle': 'Сапа мен үлгерімдің бағаналық диаграммалары',
        'metrics_tab_overall': 'Жалпы',
        'metrics_tab_parallel': 'Параллельдер бойынша',
        'metrics_download_overall': 'Excel жүктеу — жалпы',
        'metrics_download_parallel': 'Excel жүктеу — параллельдер бойынша',
        'metrics_card_1_4': '1–4 сыныптар',
        'metrics_card_5_9': '5–9 сыныптар',
        'metrics_card_9_11': '9–11 сыныптар',
        'metrics_card_9': '9 сынып',
        'metrics_card_11': '11 сынып',
        'metrics_empty_1_4': '1–4 сынып тобы үшін дерек жоқ.',
        'metrics_empty_5_9': '5–9 сынып тобы үшін дерек жоқ.',
        'metrics_empty_9_11': '9–11 сынып тобы үшін дерек жоқ.',
        'metrics_empty_9': '9 сынып үшін дерек жоқ.',
        'metrics_empty_11': '11 сынып үшін дерек жоқ.',
        'metrics_no_charts': 'Диаграммалар құру үшін дерек жоқ.',
        'metrics_col_indicator': 'Көрсеткіш',
        'metrics_col_total': 'Жиынтығы',
        'metrics_row_quality': 'Сапа, %',
        'metrics_row_success': 'Үлгерім, %',
        'metrics_chart_quality': 'Сапа',
        'metrics_chart_success': 'Үлгерім',
        'metrics_class_word': 'сынып',
        'metrics_parallel_empty': '{grade} сыныпы үшін дерек жоқ.',
        'metrics_excel_sheet_tables': 'Кестелер',
        'metrics_excel_period_q1': '1-ші тоқсан',
        'metrics_excel_period_q2': '2-ші тоқсан',
        'metrics_excel_period_q3': '3-ші тоқсан',
        'metrics_excel_period_q4': '4-ші тоқсан',
        'metrics_excel_period_year': 'Оқу жылы',
        'metrics_excel_period_fallback': '{n}-ші тоқсан',
        'metrics_excel_title': 'Сыныптар бойынша статистика',
        'metrics_excel_subtitle': 'Сыныптар бойынша сапа мен үлгерім',
        'metrics_excel_note_overall': 'Кестелер мен қорытынды — осы бетте; гистограммалар — келесілерде (дерек осыдан).',
        'metrics_excel_note_parallel': 'Параллельдер бойынша кестелер — осы бетте; гистограммалар — келесілерде.',
        'metrics_excel_section_overall': 'Жалпы',
        'metrics_excel_section_parallel': 'Параллельдер бойынша',
        'metrics_excel_section_summary': 'Қорытынды',
        'metrics_excel_sec_1_4': '1–4 сыныптар',
        'metrics_excel_sec_5_9': '5–9 сыныптар',
        'metrics_excel_sec_9_11': '9–11 сыныптар',
        'metrics_excel_sec_9': '9 сынып',
        'metrics_excel_sec_11': '11 сынып',
        'metrics_excel_empty_1_4': '1–4 сынып тобы үшін дерек жоқ.',
        'metrics_excel_empty_5_9': '5–9 сынып тобы үшін дерек жоқ.',
        'metrics_excel_empty_9_11': '9–11 сынып тобы үшін дерек жоқ.',
        'metrics_excel_empty_9': '9 сынып үшін дерек жоқ.',
        'metrics_excel_empty_11': '11 сынып үшін дерек жоқ.',
        'metrics_excel_school_weighted': 'Мектеп бойынша (арифметикалық орташа)',
        'metrics_excel_parallel_1_4': '1–4 параллельдер',
        'metrics_excel_parallel_5_9': '5–9 параллельдер',
        'metrics_excel_parallel_10_11': '10–11 параллельдер',
        'metrics_excel_fn_pattern': 'Сыныптар_статистикасы_{period}т__{suffix}.xlsx',
        'metrics_excel_fn_suf_o': 'жалпы',
        'metrics_excel_fn_suf_p': 'параллельдер',

        # Final school report
        'final_report_title': 'Мектептің қорытынды есебі',
        'final_report_input_title': 'Қорытынды есеп — деректер енгізу',
        'final_report_input_hint': 'Аттестаттар және үздік оқушылар (қолмен нақтылайтын деректер)',
        'final_report_input_nav_desc': 'Аттестаттар және үздік оқушылар',
        'final_report_export_btn': 'Қорытынды есепті қалыптастыру',
        'final_report_export_desc': 'Қорытынды, графиктер және динамикамен Excel',
        'final_report_tab_awards': 'Аттестаттар',
        'final_report_awards_hint': 'Үздік аттестаттар және «Алтын белгі»',
        'final_report_awards_altyn': 'Алтын белгі',
        'final_report_awards_excellent_11': 'Үздік (11 сынып)',
        'final_report_awards_excellent_9': 'Үздік (9 сынып)',
        'final_report_awards_students': 'Үздік оқушылар тізімі (JSON)',
        'final_report_awards_students_hint': 'Мысал: [{"name":"Иванов И.","award":"altyn_belgi"}]',
        'final_report_sheet_summary': 'Қорытынды',
        'final_report_sheet_dynamics': 'Тіркелім динамикасы',
        'final_report_sheet_enrollment': 'Тіркелім',
        'final_report_sheet_classes': 'Сыныптар бойынша үлгерім',
        'final_report_sheet_parallels': 'Сатылар бойынша',
        'final_report_sheet_quarters': 'Тоқсандар бойынша',
        'final_report_sheet_subjects': 'Пәндер бойынша сапа',
        'final_report_sheet_problems': 'Мәселелі аймақтар',
        'final_report_sheet_excellent': 'Үздік оқушылар',
        'final_report_sheet_awards': 'Аттестаттар',
        'final_report_sheet_gia9': 'МЖА-9',
        'final_report_sheet_gia11': 'МЖА-11',
        'final_report_sheet_ent': 'ҰБТ',
        'final_report_chart_ent': 'ҰБТ динамикасы',
        'final_report_ent_col_period': 'Кезең',
        'final_report_ent_col_count': 'Тапсырған саны',
        'final_report_ent_col_avg': 'Орташа балл',
        'final_report_ent_col_max': 'Максимум',
        'final_report_ent_forecast': 'Орташа балл болжамы',
        'final_report_recommendations': 'Ұсыныстар',
        'final_report_chart_quarters': 'Тоқсандар динамикасы',
        'final_report_col_total_students': 'Барлық оқушылар',
        'final_report_col_total_classes': 'Сынып-комплекттер',
        'final_report_col_avg_fill': 'Орташа толтырылу',
        'final_report_col_students': 'Оқушылар',
        'final_report_col_on_5': '«5»',
        'final_report_col_on_4': '«4»',
        'final_report_col_one_3': 'Бір «3»',
        'final_report_col_two_3': 'Екі «3» және көп',
        'final_report_col_on_3': '«3»',
        'final_report_col_on_2': '«2»',
        'final_report_col_stage': 'Саты',
        'final_report_col_classes_with_data': 'Дерек бар сыныптар',
        'final_report_col_student_name': 'Аты-жөні',
        'final_report_col_award_type': 'Аттестат түрі',
        'final_report_rec_weak': 'Әлсіз оқушылармен жұмыс ұйымдастыру',
        'final_report_rec_math': 'Математика бойынша бақылау кесінділерін жүргізу',
        'final_report_dynamics_title': '3 ЖЫЛДА ОҚУШЫЛАР КОНТИНГЕНТІНІҢ САНЫ ДИНАМИКАСЫ',
        'final_report_col_parameters': 'Параметрлер',
        'final_report_students_begin': 'Жыл басындағы оқушылар саны:',
        'final_report_students_end': 'Жыл соңындағы оқушылар саны:',
        'final_report_class_sets_begin': 'Жыл басындағы сынып-комплекттер:',
        'final_report_avg_fill': 'Сыныптардың орташа толтырылуы:',
        'final_report_stage_primary': 'бастауыш мектеп',
        'final_report_stage_basic': 'негізгі мектеп',
        'final_report_stage_secondary': 'орта мектеп',
        'final_report_no_data': '-',
        'final_report_sheet_quality': 'Сатылар бойынша сапа',
        'final_report_quality_title': 'ОҚУ САТЫЛАРЫНЫҢ КӨРСЕТКІШТЕРІ',
        'final_report_hdr_q1': '1 тоқсан',
        'final_report_hdr_q2': '2 тоқсан',
        'final_report_hdr_q3': '3 тоқсан',
        'final_report_hdr_q4': '4 тоқсан',
        'final_report_hdr_total': 'Қорытынды',
        'final_report_grade_row_5': '«5»',
        'final_report_grade_row_4': '«4»',
        'final_report_grade_row_3': '«3»',
        'final_report_grade_row_2': '«2»',
        'final_report_chart_grades_2_11': '2-11 сыныптардың жалпы динамикасы',
        'final_report_chart_quality_2_11': '2-11 сыныптарда білім сапасы мен үлгерім динамикасы',
        'final_report_chart_y_students': 'Оқушылар саны',
        'final_report_chart_y_percent': 'Пайыз (%)',
        'academic_year_label': 'Оқу жылы',
        'notes_label': 'Ескертпелер',
        'save': 'Сақтау',

        # Cross-school reports protection
        'cross_school_label': 'Басқа мектептер үшін есептер',
        'cross_school_description': 'Өшірілсе — мұғалім тек өз ұйымы үшін есептер жасай алады. Аккаунтты таратудан қорғау.',
        'cross_school_enabled': 'Рұқсат етілді (өшіру)',
        'cross_school_disabled': 'Тыйым салынды (қосу)',
    }
}


def gettext(key, lang='ru'):
    """Get translation for key"""
    return TRANSLATIONS.get(lang, {}).get(key, key)
