"""
Simple translation system for web app
"""

TRANSLATIONS = {
    'ru': {
        # Common
        'login': 'Вход',
        'logout': 'Выйти',
        'username': 'Логин',
        'password': 'Пароль',
        'dashboard': 'Панель управления',
        'settings': 'Настройки',
        
        # Teacher Dashboard
        'teacher_dashboard': 'Кабинет учителя',
        'scraper': 'Скрапер',
        'mektep_login': 'Логин/IIN (mektep.edu.kz)',
        'mektep_password': 'Пароль (mektep.edu.kz)',
        'language': 'Язык',
        'quarter': 'Четверть',
        'quarter_1': '1 четверть',
        'quarter_2': '2 четверть (1 полугодие)',
        'quarter_3': '3 четверть',
        'quarter_4': '4 четверть (2 полугодие)',
        'start_button': 'Запустить',
        'progress': 'Прогресс',
        'status': 'Статус',
        'jobs': 'Задачи',
        'reports': 'Отчеты',
        'my_files': 'Мои файлы',
        'goals': 'Цели',
        'download_all': 'Скачать все отчеты',
        'delete_all': 'Удалить все отчеты',
        'class': 'Класс',
        'subject': 'Предмет',
        'download': 'Скачать',
        'number': '№',
        'excel': 'Excel',
        'word': 'Word',
        'no_files': 'Файлов пока нет. Запустите скрапер, чтобы создать отчеты.',
        'apply': 'Применить',
        'cancel': 'Отмена',
        'goals_modal_title': 'Цели обучения',
        'select_reports': 'Выберите отчеты для применения:',
        'no_reports_available': 'Нет доступных отчетов',
        'goals_difficulties': 'Цели, вызвавшие затруднения',
        'achieved_goals': 'Цели, которые были достигнуты',
        'difficulties_list': 'Перечень затруднений, которые возникли у обучающихся при выполнении заданий',
        'reasons': 'Причины, указанных выше затруднений у обучающихся при выполнении заданий',
        'correction': 'Планируемая коррекционная работа',
        'difficulties_correction_title': 'Затруднения и коррекционная работа',

        # Admin Dashboard
        'admin_panel': 'Панель управления',
        'grades_overview': 'Обзор оценок',
        'grades_overview_desc': 'Сводные таблицы по классам',
        'analytics_sor_soch': 'Аналитика СОР/СОЧ',
        'analytics_sor_soch_desc': 'Анализ суммативного оценивания',
        'class_teacher_report': 'Отчёт кл. руководителя',
        'student_categories': 'Категории учеников',
        'management': 'Управление',
        'management_desc': 'Учителя, классы, предметы',
        'teachers': 'Учителя',
        'classes': 'Классы',
        'teacher_fio': 'ФИО учителя',
        'teacher_login': 'Логин учителя',
        'add_btn': '+ Добавить',
        'fio': 'ФИО',
        'login_col': 'Логин',
        'actions': 'Действия',
        'password_btn': 'Пароль',
        'class_name_placeholder': 'Название класса (напр. 7А)',
        'class_teacher': 'Классный руководитель',
        'not_assigned': '— не назначен —',
        'no_classes': 'Нет классов. Добавьте класс выше.',
        'edit_class': 'Редактировать класс',
        'edit_teacher_fio': 'Редактировать ФИО учителя',
        'class_name_label': 'Название класса:',
        'class_teacher_label': 'Классный руководитель:',
        'fio_label': 'ФИО:',
        'save_btn': 'Сохранить',
        'cancel_btn': 'Отмена',
        'password_label': 'Пароль:',
        'current_password': 'Текущий пароль:',
        'new_password': 'Новый пароль:',
        'min_4_chars': 'Минимум 4 символа',
        'change_password': 'Изменить пароль',
        'copy_btn': 'Копировать',
        'copied': 'Скопировано!',
        'loading_text': 'Загрузка...',
        'load_error': 'Ошибка загрузки',
        'not_available': 'Недоступен',
        'confirm_delete_teacher': 'Вы уверены, что хотите удалить учителя "{}"?\n\nВсе данные учителя (отчёты, назначения) будут удалены безвозвратно.',
        'confirm_delete_class': 'Удалить класс «{}»?',

        # Grades Overview
        'period_type': 'Тип периода',
        'quarter_label': 'Четверть',
        'semester_label': 'Полугодие',
        'period_number': 'Номер периода',
        'quarter_suffix': 'четверть',
        'semester_suffix': 'полугодие',
        'apply_btn': 'Применить',
        'class_col': 'Класс',
        'students_count': 'Кол-во учеников',
        'subjects': 'Предметы',
        'subjects_count': 'предметов',
        'summary_table': 'Сводная таблица',
        'no_data_period': 'Нет данных за выбранный период. Учителя ещё не загрузили отчёты.',

        # Analytics
        'analytics': 'Анализы',
        'analytics_desc': 'Просмотр статистики по предметам',
        'all_subjects': 'Все предметы',
        'all_classes': 'Все классы',
        'teacher_col': 'Учитель',
        'all_teachers': 'Все учителя',
        'reset_filters': 'Сбросить фильтры',
        'sor': 'СОР',
        'soch': 'СОЧ',
        'grades': 'Оценки',
        'total': 'Всего',
        'quality_pct': 'Качество, %',
        'success_pct': 'Успеваемость, %',
        'no_data_sor': 'Нет данных по СОР.',
        'no_data_soch': 'Нет данных по СОЧ.',
        'no_data_grades': 'Нет данных по оценкам.',

        # Class Teacher Report
        'class_teacher_full_report': 'Отчет классных руководителей',
        'download_excel': 'Скачать Excel',
        'on_5': 'на 5',
        'on_4': 'на 4',
        'with_one_4': 'С одной 4',
        'on_3': 'на 3',
        'with_one_3': 'С одной 3',
        'underachievers': 'Неуспевающие',
        'search_placeholder': 'Поиск по классу или ФИО...',
        'subject_col': 'Предмет',
        'subject_1': 'Предмет 1',
        'subject_2': 'Предмет 2',
        'subject_3': 'Предмет 3',
        'subject_4': 'Предмет 4',
        'subject_5plus': 'Предмет 5+',
        'no_data': 'Нет данных',

        # Grades Class (summary table)
        'summary_table_grades': 'Сводная таблица оценок',
        'total_students': 'Всего учеников',
        'quality_label': 'Качество',
        'success_label': 'Успеваемость',
        'distribution': 'Распределение',
        'grades_by_subjects': 'Оценки по предметам',
        'student_fio': 'ФИО ученика',
        'count_5': 'Кол-во «5»',
        'count_4': 'Кол-во «4»',
        'count_3': 'Кол-во «3»',
        'quality_pct_label': 'Качество %',
        'success_pct_label': 'Успеваемость %',
        'no_data_class_grades': 'Нет данных по оценкам для этого класса.',

        # Subject Detail
        'all_subjects_sidebar': 'Все предметы',
        'subject_teachers': 'Учителя предмета',
        'select_teacher': '— Выберите учителя —',
        'add_teacher': 'Добавить учителя',
        'remove_btn': 'Убрать',
        'confirm_remove_teacher': 'Удалить учителя «{}» из предмета? Все закреплённые классы также будут удалены.',
        'assigned_classes': 'Закреплённые классы:',
        'subgroup': 'Подгруппа',
        'subgroup_label': 'Подгруппа',
        'whole_class': 'Весь класс',
        'confirm_unassign_class': 'Открепить класс {}?',
        'no_assigned_classes': 'Нет закреплённых классов',
        'select_class': '— Выберите класс —',
        'assign_class': 'Закрепить класс',
        'no_subject_teachers': 'Нет учителей для этого предмета. Добавьте учителя выше.',

        # Password page
        'user_password': 'Пароль пользователя',
        'password_unavailable': 'Пароль недоступен',
        'back_btn': 'Назад',

        # School Detail (superadmin)
        'superadmin': 'Супер-админ',
        'active_status': 'Активна',
        'inactive_status': 'Неактивна',
        'admins_count_label': 'Админов',
        'teachers_count_label': 'Учителей',
        'classes_count_label': 'Классов',
        'subjects_count_label': 'Предметов',
        'administrators': 'Администраторы',
        'no_admins': 'Нет администраторов',
        'name_col': 'Имя',
        'no_teachers': 'Нет учителей',
        'no_classes_short': 'Нет классов',
        'teachers_badge': 'учителей',
        'no_subjects': 'Нет предметов (данные появятся после скрапинга)',

        # Superadmin Dashboard
        'super_admin': 'Super Admin',
        'teacher_cabinet_reports': 'Кабинет учителя / Создание отчётов',
        'schools': 'Школы',
        'new_school_placeholder': 'Название новой школы',
        'add_short': 'Добавить',
        'open_status': 'Открыт',
        'closed_status': 'Закрыт',
        'settings_btn': 'Настройки',
        'close_school': 'Закрыть',
        'open_school': 'Открыть',
        'delete_btn': 'Удалить',
        'scrape_limit_label': 'Лимит скрапов / четверть',
        'ai_api_key_label': 'AI API ключ',
        'ai_model_label': 'Модель AI',
        'reset_counter': 'Сбросить счётчик',
        'confirm_reset_counter': 'Сбросить счётчик скрапов для «{}»?',
        'no_schools': 'Школы ещё не добавлены.',
        'school_admins': 'Админы школ',
        'select_school': 'Выберите школу…',
        'admin_fio_placeholder': 'ФИО админа',
        'admin_login_placeholder': 'Логин нового админа',
        'school_col': 'Школа',
        'no_school_admins': 'Админы ещё не добавлены.',
        'edit_admin_fio': 'Редактировать ФИО администратора',
        'confirm_delete_admin': 'Вы уверены, что хотите удалить администратора "{}"?\n\nЭто действие необратимо.',
        'confirm_delete_school': 'Вы уверены, что хотите удалить школу "{}"?\n\nБудут удалены ВСЕ данные: учителя, админы, классы, отчёты.\n\nЭто действие необратимо!',

        # Cross-school reports protection
        'cross_school_label': 'Отчёты для других школ',
        'cross_school_description': 'Если выключено — учитель может создавать отчёты только для своей организации. Защита от передачи аккаунта.',
        'cross_school_enabled': 'Разрешено (выключить)',
        'cross_school_disabled': 'Запрещено (включить)',
    },
    'kk': {
        # Common
        'login': 'Кіру',
        'logout': 'Шығу',
        'username': 'Логин',
        'password': 'Құпия сөз',
        'dashboard': 'Басқару панелі',
        'settings': 'Баптаулар',
        
        # Teacher Dashboard
        'teacher_dashboard': 'Мұғалім кабинеті',
        'scraper': 'Скрапер',
        'mektep_login': 'Логин/ЖСН (mektep.edu.kz)',
        'mektep_password': 'Құпия сөз (mektep.edu.kz)',
        'language': 'Тіл',
        'quarter': 'Тоқсан',
        'quarter_1': '1 тоқсан',
        'quarter_2': '2 тоқсан (1 жартыжылдық)',
        'quarter_3': '3 тоқсан',
        'quarter_4': '4 тоқсан (2 жартыжылдық)',
        'start_button': 'Іске қосу',
        'progress': 'Прогресс',
        'status': 'Күй',
        'jobs': 'Тапсырмалар',
        'reports': 'Есептер',
        'my_files': 'Менің файлдарым',
        'goals': 'Мақсаттар',
        'download_all': 'Барлық есептерді жүктеу',
        'delete_all': 'Барлық есептерді жою',
        'class': 'Сынып',
        'subject': 'Пән',
        'download': 'Жүктеу',
        'number': '№',
        'excel': 'Excel',
        'word': 'Word',
        'no_files': 'Файлдар әзірге жоқ. Есептер жасау үшін скраперді іске қосыңыз.',
        'apply': 'Қолдану',
        'cancel': 'Болдырмау',
        'goals_modal_title': 'Оқыту мақсаттары',
        'select_reports': 'Қолдану үшін есептерді таңдаңыз:',
        'no_reports_available': 'Қолжетімді есептер жоқ',
        'goals_difficulties': 'Қиындық тудырған мақсаттар',
        'achieved_goals': 'Қол жеткізілген мақсаттар',
        'difficulties_list': 'Тапсырмаларды орындау кезінде оқушыларда туындаған қиындықтар тізімі',
        'reasons': 'Тапсырмаларды орындау кезінде оқушылардың жоғарыда аталған қиындықтарының себептері',
        'correction': 'Жоспарланған түзету жұмысы',
        'difficulties_correction_title': 'Қиындықтар және түзету жұмысы',

        # Admin Dashboard
        'admin_panel': 'Басқару панелі',
        'grades_overview': 'Бағаларға шолу',
        'grades_overview_desc': 'Сыныптар бойынша жиынтық кестелер',
        'analytics_sor_soch': 'БЖБ/ТЖБ аналитикасы',
        'analytics_sor_soch_desc': 'Жиынтық бағалауды талдау',
        'class_teacher_report': 'Сынып жетекшісі есебі',
        'student_categories': 'Оқушылар санаттары',
        'management': 'Басқару',
        'management_desc': 'Мұғалімдер, сыныптар, пәндер',
        'teachers': 'Мұғалімдер',
        'classes': 'Сыныптар',
        'teacher_fio': 'Мұғалімнің аты-жөні',
        'teacher_login': 'Мұғалімнің логині',
        'add_btn': '+ Қосу',
        'fio': 'Аты-жөні',
        'login_col': 'Логин',
        'actions': 'Әрекеттер',
        'password_btn': 'Құпия сөз',
        'class_name_placeholder': 'Сынып атауы (мыс. 7А)',
        'class_teacher': 'Сынып жетекшісі',
        'not_assigned': '— тағайындалмаған —',
        'no_classes': 'Сыныптар жоқ. Жоғарыдан сынып қосыңыз.',
        'edit_class': 'Сыныпты өңдеу',
        'edit_teacher_fio': 'Мұғалімнің аты-жөнін өңдеу',
        'class_name_label': 'Сынып атауы:',
        'class_teacher_label': 'Сынып жетекшісі:',
        'fio_label': 'Аты-жөні:',
        'save_btn': 'Сақтау',
        'cancel_btn': 'Болдырмау',
        'password_label': 'Құпия сөз:',
        'current_password': 'Ағымдағы құпия сөз:',
        'new_password': 'Жаңа құпия сөз:',
        'min_4_chars': 'Кемінде 4 таңба',
        'change_password': 'Құпия сөзді өзгерту',
        'copy_btn': 'Көшіру',
        'copied': 'Көшірілді!',
        'loading_text': 'Жүктелуде...',
        'load_error': 'Жүктеу қатесі',
        'not_available': 'Қолжетімсіз',
        'confirm_delete_teacher': 'Сіз "{}" мұғалімін жоюға сенімдісіз бе?\n\nМұғалімнің барлық деректері (есептер, тағайындаулар) қайтарымсыз жойылады.',
        'confirm_delete_class': '«{}» сыныбын жою керек пе?',

        # Grades Overview
        'period_type': 'Кезең түрі',
        'quarter_label': 'Тоқсан',
        'semester_label': 'Жартыжылдық',
        'period_number': 'Кезең нөмірі',
        'quarter_suffix': 'тоқсан',
        'semester_suffix': 'жартыжылдық',
        'apply_btn': 'Қолдану',
        'class_col': 'Сынып',
        'students_count': 'Оқушылар саны',
        'subjects': 'Пәндер',
        'subjects_count': 'пән',
        'summary_table': 'Жиынтық кесте',
        'no_data_period': 'Таңдалған кезең бойынша деректер жоқ. Мұғалімдер есептерді әлі жүктемеген.',

        # Analytics
        'analytics': 'Талдаулар',
        'analytics_desc': 'Пәндер бойынша статистиканы қарау',
        'all_subjects': 'Барлық пәндер',
        'all_classes': 'Барлық сыныптар',
        'teacher_col': 'Мұғалім',
        'all_teachers': 'Барлық мұғалімдер',
        'reset_filters': 'Сүзгілерді қалпына келтіру',
        'sor': 'БЖБ',
        'soch': 'ТЖБ',
        'grades': 'Бағалар',
        'total': 'Барлығы',
        'quality_pct': 'Сапа, %',
        'success_pct': 'Үлгерім, %',
        'no_data_sor': 'БЖБ бойынша деректер жоқ.',
        'no_data_soch': 'ТЖБ бойынша деректер жоқ.',
        'no_data_grades': 'Бағалар бойынша деректер жоқ.',

        # Class Teacher Report
        'class_teacher_full_report': 'Сынып жетекшілерінің есебі',
        'download_excel': 'Excel жүктеу',
        'on_5': '5-ке',
        'on_4': '4-ке',
        'with_one_4': 'Бір 4-пен',
        'on_3': '3-ке',
        'with_one_3': 'Бір 3-пен',
        'underachievers': 'Үлгермейтіндер',
        'search_placeholder': 'Сынып немесе аты-жөні бойынша іздеу...',
        'subject_col': 'Пән',
        'subject_1': 'Пән 1',
        'subject_2': 'Пән 2',
        'subject_3': 'Пән 3',
        'subject_4': 'Пән 4',
        'subject_5plus': 'Пән 5+',
        'no_data': 'Деректер жоқ',

        # Grades Class (summary table)
        'summary_table_grades': 'Бағалардың жиынтық кестесі',
        'total_students': 'Барлық оқушылар',
        'quality_label': 'Сапа',
        'success_label': 'Үлгерім',
        'distribution': 'Бөлу',
        'grades_by_subjects': 'Пәндер бойынша бағалар',
        'student_fio': 'Оқушының аты-жөні',
        'count_5': '«5» саны',
        'count_4': '«4» саны',
        'count_3': '«3» саны',
        'quality_pct_label': 'Сапа %',
        'success_pct_label': 'Үлгерім %',
        'no_data_class_grades': 'Бұл сынып бойынша бағалар деректері жоқ.',

        # Subject Detail
        'all_subjects_sidebar': 'Барлық пәндер',
        'subject_teachers': 'Пән мұғалімдері',
        'select_teacher': '— Мұғалімді таңдаңыз —',
        'add_teacher': 'Мұғалім қосу',
        'remove_btn': 'Алып тастау',
        'confirm_remove_teacher': '«{}» мұғалімін пәннен жою керек пе? Барлық бекітілген сыныптар да жойылады.',
        'assigned_classes': 'Бекітілген сыныптар:',
        'subgroup': 'Топша',
        'subgroup_label': 'Топша',
        'whole_class': 'Бүкіл сынып',
        'confirm_unassign_class': '{} сыныбын ажырату керек пе?',
        'no_assigned_classes': 'Бекітілген сыныптар жоқ',
        'select_class': '— Сыныпты таңдаңыз —',
        'assign_class': 'Сыныпты бекіту',
        'no_subject_teachers': 'Бұл пәнде мұғалімдер жоқ. Жоғарыдан мұғалім қосыңыз.',

        # Password page
        'user_password': 'Пайдаланушы құпия сөзі',
        'password_unavailable': 'Құпия сөз қолжетімсіз',
        'back_btn': 'Артқа',

        # School Detail (superadmin)
        'superadmin': 'Супер-админ',
        'active_status': 'Белсенді',
        'inactive_status': 'Белсенді емес',
        'admins_count_label': 'Әкімшілер',
        'teachers_count_label': 'Мұғалімдер',
        'classes_count_label': 'Сыныптар',
        'subjects_count_label': 'Пәндер',
        'administrators': 'Әкімшілер',
        'no_admins': 'Әкімшілер жоқ',
        'name_col': 'Аты',
        'no_teachers': 'Мұғалімдер жоқ',
        'no_classes_short': 'Сыныптар жоқ',
        'teachers_badge': 'мұғалім',
        'no_subjects': 'Пәндер жоқ (деректер скрапингтен кейін пайда болады)',

        # Superadmin Dashboard
        'super_admin': 'Super Admin',
        'teacher_cabinet_reports': 'Мұғалім кабинеті / Есептер жасау',
        'schools': 'Мектептер',
        'new_school_placeholder': 'Жаңа мектеп атауы',
        'add_short': 'Қосу',
        'open_status': 'Ашық',
        'closed_status': 'Жабық',
        'settings_btn': 'Баптаулар',
        'close_school': 'Жабу',
        'open_school': 'Ашу',
        'delete_btn': 'Жою',
        'scrape_limit_label': 'Скрап лимиті / тоқсан',
        'ai_api_key_label': 'AI API кілті',
        'ai_model_label': 'AI моделі',
        'reset_counter': 'Есептегішті қалпына келтіру',
        'confirm_reset_counter': '«{}» үшін скрап есептегішін қалпына келтіру керек пе?',
        'no_schools': 'Мектептер әлі қосылмаған.',
        'school_admins': 'Мектеп әкімшілері',
        'select_school': 'Мектепті таңдаңыз…',
        'admin_fio_placeholder': 'Әкімші аты-жөні',
        'admin_login_placeholder': 'Жаңа әкімші логині',
        'school_col': 'Мектеп',
        'no_school_admins': 'Әкімшілер әлі қосылмаған.',
        'edit_admin_fio': 'Әкімші аты-жөнін өңдеу',
        'confirm_delete_admin': 'Сіз "{}" әкімшісін жоюға сенімдісіз бе?\n\nБұл әрекет қайтарымсыз.',
        'confirm_delete_school': 'Сіз "{}" мектебін жоюға сенімдісіз бе?\n\nБАРЛЫҚ деректер жойылады: мұғалімдер, әкімшілер, сыныптар, есептер.\n\nБұл әрекет қайтарымсыз!',

        # Cross-school reports protection
        'cross_school_label': 'Басқа мектептер үшін есептер',
        'cross_school_description': 'Өшірілсе — мұғалім тек өз ұйымы үшін есептер жасай алады. Аккаунтты таратудан қорғау.',
        'cross_school_enabled': 'Рұқсат етілді (өшіру)',
        'cross_school_disabled': 'Тыйым салынды (қосу)',
    }
}


def gettext(key, lang='ru'):
    """Get translation for key"""
    return TRANSLATIONS.get(lang, {}).get(key, key)
